services:
  n8n:
    build: .
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Belem
      - GENERIC_TIMEZONE=America/Belem
      - N8N_ENABLE_EXECUTE_COMMAND=true
      - N8N_ENABLE_UNSAFE_CORE_NODES=true
      - NODES_EXCLUDE=[]
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/home/node/.n8n-files
    command: start

volumes:
  n8n_data: